# name: Deploy NodeJS Application on Hostinger VPS

# on:
#  push:
#   branches:
#          -maina

#  jobs:
#    deploy:
#      rurns-on: 
#           -ubuntu-latest        

#      steps:
#         - name: 📥 Checkout code
#           uses: actions/checkout@v4  

#         - name: 🐳 Build Docker images
#           run: docker compose build 